### ISSUE TITLE
Explain in docs how to use

### ISSUE THREAD

**Issue by Garrett-R** [fengsp/flask-profile#4]
This tool looks pretty cool.  Do you mind explaining exactly how to use it?

I added all the lines of code in the README.md, then started my app with `./app.py`.  I visited a couple pages, then hit <kbd>CTRL</kbd><kbd>C</kbd> to kill the server.  But I'm not sure where to find the results of the profiling.  Are they saved into some file on disk?

**Comment by kaka1909** [comment]
I've read the code and get known the profiling result will only be recorded using render_template(flask method) when your route is used for page response(response.headers['content-type'].startswith('text/html')) rather than any response like json or others. So it does not fit my demands. If you are the right user, you will see the profiling result html elements at the end of your own page.

**Comment by fengsp** [comment]
Yes, it only works if your response is one html page because the result is showed in html.

**Comment by fengsp** [comment]
I added a note in the README.
